jobs:
  - job: Backend
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: |
        echo Backend Tests
  - job: Frontend
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '9.7.1'
      displayName: 'Install Node'
    - script: |
        echo 'Frontend Tests'
        dir
        npm install
        npm run test -- --verbose --notify
        echo 'Done tests :)'
      workingDirectory: frontend/mobilityai_react
  - job: Machine_Learning
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: |
        echo Machine Learning Tests
