jobs:
  - job: Backend
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: |
        echo Backend Tests
  - job: Frontend
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: |
        echo Frontend Tests
  - job: Machine_Learning
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    - script: |
        echo Machine Learning Tests
        cd machine_learning
        pip install pipenv
        pipenv shell
        pipenv install
        pytest
