jobs:
  - job: Backend
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: |
        echo Backend Tests
  - job: Frontend
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '9.7.1'
      displayName: 'Install Node'
    - script: npm install
      workingDirectory: frontend/mobilityai_react
      displayName: 'Install dependencies"
    - script: npm run test-ci
      workingDirectory: frontend/mobilityai_react
      displayName: 'Run tests'
  - job: Machine_Learning
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: |
        echo Machine Learning Tests
