jobs:
  - job: Backend
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: |
        echo Backend Tests
  - job: Frontend
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '9.7.1'
      displayName: 'Install Node'
    - script: cd frontend/mobilityai_react
      displayName: 'Enter frontend folder'
    - script: npm install
      displayName: 'Install dependencies'
    - script: npm run test
      displayName: 'Run unit tests'
  - job: Machine_Learning
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: |
        echo Machine Learning Tests