version: "3"
services:
  web:
    build: "backend/mobilityAI/"
    ports: 
      - "80:80"
    depends_on:
      - db
      - ml
  ml:
    build: "machine_learning/"
    ports:
      - "6000:6000"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password