version: 2
jobs:
  build:
    working_directory: ~/4zp6
    docker:
      - image: node:10-browsers
    steps:
      - checkout
      - run:
          name: Go to front end
          command: cd frontend/mobilityai/
      - run:
          name: Install node modules with npm
          command: npm install
      - run:
          name: Run tests with npm
          command: CI=true npm test
