version: 2
jobs:
  build:
    working_directory: ~/4zp6
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: Install node modules with npm
          command: cd frontend/mobilityai && npm install
      - run:
          name: Run tests with npm
          command: cd frontend/mobilityai && CI=true npm test
