version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Front End
          commands:
            - cd frontend/mobilityai/
            - npm install
            - CI=true npm test
      - run:
          name: Back end
          command: echo TODO back end tests
